<?php

namespace Plugin\BpmLinkPaymentGateway\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BpmcOrderPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BpmcOrderPaymentRepository extends EntityRepository
{
}
